# Generated by Django 5.0.1 on 2024-02-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Eid', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=200)),
                ('Eloc', models.CharField(max_length=200)),
                ('Ejob', models.CharField(max_length=200)),
                ('Esal', models.PositiveIntegerField()),
            ],
        ),
    ]
