# Generated by Django 5.0.1 on 2024-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=200)),
                ('Csalary', models.PositiveIntegerField()),
                ('Caddress', models.CharField(max_length=200)),
            ],
        ),
    ]
